Corrected error file name

diff --git a/Advanced_shell/apiAutomation-0x00 b/Advanced_shell/apiAutomation-0x00
--- a/Advanced_shell/apiAutomation-0x00
+++ b/Advanced_shell/apiAutomation-0x00
@@ -5,5 +5,5 @@ json=$(curl https://pokeapi.co/api/v2/pokemon/)
 if [ $? -eq 0 ]; then
     echo $json > data.json
 else
-    echo "Error code: $?" > error.txt
+    echo "Error code: $?" > errors.txt
 fi
